# format = """
# [░](#a3aed2)\
# $fill\
# [░ ](#a3aed2)\
# $line_break\
# [░](#a3aed2)\
# $fill\
# [░ ](#a3aed2)\
# $line_break\
# $character\
# """

format = """
$character
"""

right_format = """
[($status)](bold bright-red)
[($cmd_duration)](bold bright-blue)
[($memory_usage)](bold bright-green) \
$sudo$jobs
[❮](#a3aed2)
"""

# Disable the blank line at the start of the prompt
add_newline = false
command_timeout = 3000

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
min_time = 500
style = 'bg:bright-blue'
format = '[$duration]($style)'

[memory_usage]
disabled = false
threshold = -1
format ='[${ram}]($style)'
style = 'bg:bright-green'

[status]
disabled = false
style = "bg:bright-red"
format = "[$symbol$status( 飯$signal_name)]($style)"
symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = "ﰸ"
signal_symbol = "⚡"
map_symbol = true
pipestatus = true
pipestatus_separator = "|"
pipestatus_segment_format = "$symbol$status( 飯$signal_name)"
pipestatus_format ='[\[$pipestatus\]]($style)'

[sudo]
style = 'bold green'
format = '[$symbol]($style) '
symbol = ''
disabled = false
